module.exports.config = {
    name: "emoji_voice",
    version: "10.1", // সংস্করণ আপডেট করা হলো
    hasPermssion: 0,
    credits: "☞︎︎︎𝐑𝐀𝐁𝐁i⍟𝐕𝐀𝐈☜︎︎",
    description: "Emoji দিলে কিউট মেয়ের ভয়েস পাঠাবে 😍",
    commandCategory: "noprefix",
    usages: "😘🥰😍",
    cooldowns: 2 // কমালে দ্রুত রিপ্লাই দিতে পারবে
};

const axios = require("axios");
const fs = require("fs");
const path = require("path");

const emojiAudioMap = {
    "🥱": "https://files.catbox.moe/9pou40.mp3",
    "😁": "https://files.catbox.moe/60cwcg.mp3",
    "😌": "https://files.catbox.moe/epqwbx.mp3",
    "🥺": "https://files.catbox.moe/wc17iq.mp3",
    "🤭": "https://files.catbox.moe/cu0mpy.mp3",
    "😅": "https://files.catbox.moe/jl3pzb.mp3",
    "😏": "https://files.catbox.moe/z9e52r.mp3",
    "😞": "https://files.catbox.moe/tdimtx.mp3",
    "🤫": "https://files.catbox.moe/0uii99.mp3",
    "🍼": "https://files.catbox.moe/p6ht91.mp3",
    "🤔": "https://files.catbox.moe/hy6m6w.mp3",
    "🥰": "https://files.catbox.moe/dv9why.mp3",
    "🤦": "https://files.catbox.moe/ivlvoq.mp3",
    "😘": "https://files.catbox.moe/sbws0w.mp3",
    "😑": "https://files.catbox.moe/p78xfw.mp3",
    "😢": "https://files.catbox.moe/shxwj1.mp3",
    "🙊": "https://files.catbox.moe/3bejxv.mp3",
    "🤨": "https://files.catbox.moe/4aci0r.mp3",
    "😡": "https://files.catbox.moe/shxwj1.mp3",
    "🙈": "https://files.catbox.moe/3qc90y.mp3",
    "😍": "https://files.catbox.moe/qjfk1b.mp3",
    "😭": "https://files.catbox.moe/itm4g0.mp3",
    "😱": "https://files.catbox.moe/mu0kka.mp3",
    "😻": "https://files.catbox.moe/y8ul2j.mp3",
    "😿": "https://files.catbox.moe/tqxemm.mp3",
    "💔": "https://files.catbox.moe/6yanv3.mp3",
    "🤣": "https://files.catbox.moe/2sweut.mp3",
    "🥹": "https://files.catbox.moe/jf85xe.mp3",
    "😩": "https://files.catbox.moe/b4m5aj.mp3",
    "🫣": "https://files.catbox.moe/ttb6hi.mp3",
    "🐸": "https://files.catbox.moe/utl83s.mp3",
    "🤰": "https://files.catbox.moe/jlgowl.mp3",
    "💪": "https://files.catbox.moe/j03dk9.mp3",
    "💃": "https://files.catbox.moe/jhyng8.mp3",
    "❤️": "https://files.catbox.moe/0qgv91.mp3",
    "🥶": "https://files.catbox.moe/rzti55.mp3",
    "👀": "https://files.catbox.moe/wkdo44.mp3",
    "🙏": "https://files.catbox.moe/542hm1.mp3",
    "🐓": "https://files.catbox.moe/oaxtjv.mp3",
    "🩴": "https://files.catbox.moe/bhfqtr.mp3",
    "👑": "https://files.catbox.moe/jr4vnq.mp3",
